name: Deploy to VPS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Copy files via SSH to the VPS
      - name: Deploy files to VPS
        run: |
          rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ \
          root@85.31.239.34:/var/www/blind-test.fun/html

      # Optional: Restart the web server if needed (adjust as per your server setup)
      - name: Restart web server
        run: |
          ssh root@85.31.239.34 "sudo systemctl restart apache2"
